### ISSUE TITLE
总结：我遇到的关于3.2的若干问题与解决方法

### ISSUE THREAD

**Issue by bucket-xv** [idejie/mml-assignment3#10]
## 环境问题
1. 3.2上来就有import torch，故应当在requirements最后加入torch torchvision torchaudio，版本随意，因为不会用到
2. mml/requirements.txt要求python版本据我推测应为3.10，我这里3.12和3.9都失败过
3. mml/requirements.txt应在33行前加入 --extra-index-url https://download.pytorch.org/whl/cu118 方便requirements.txt下载，或者手动下载pytorch
4. 如果要使用Qwen2.5-0.5B代替GPT2，**需要对transformer及一系列相关package的版本进行更新！** 这意味着仅3.2B部分就会处于不同的版本中！！建议同学们在做3.2B之初就将transformer及一系列相关package的版本进行更新（**不过我没有验证过这个方法**，我自己开了两个环境，如果有同学追求稳妥也开两个就好）。我贴出我work的环境修改，**仅供参考**：transformers==4.39 huggingface-hub==0.19.3 tokenizers==0.15.2

## 代码问题
1. training.py中parser写的有点问题，无论指定-S L还是-S S都会用大的模型，可以将相关行修改为：
```python
config = ConfigL() if args.size.upper() == "L" else ConfigS()
```
2. evaluate.py中import了download_weights但没有定义，把那一行注释掉即可，然后指定好-C选项，如-C epoch_120.pt
3. evaluate.py中model.load_state_dict(checkpoint)应该改为model.load_state_dict(checkpoint['model_state_dict'])，我不是很清楚是不是因为我升级了transformer版本的缘故

## 实现的相关提示
1. 尽管数据给了val2014和train2014，但是val2014全程没有用到，忘掉这个数据集吧，train，val，test都来自train2014
2. cl_fn要返回一个attention_mask，这个通过调用tokenizer得到的，不要像我一样傻乎乎自己写，查一下transformers关于tokenizer的文档
3. 有好多函数都是助教自己实现的，不要像我一样误以为是transformers中的trainer；另外就是Net类不只有一个forward还有一个train_forward，**后者**才是关键！！

## 一点建议
1. 如果明年课程还有类似作业希望能全部用conda标明python版本或人工声明清楚。
2. 如果是新开发的作业或许直接用github repo发布会更好，这样助教打热补丁之后，同学们只要pull就可以了。
3. 注释和引导可以再细致一些，发布前后最好能让另一位助教独立复现一次，应该会少很多bug

**Comment by idejie** [comment]
非常感谢上述指正

**Comment by idejie** [comment]
一、环境问题：1.确实存在不同section使用的是不同的dependency，为了避免大家重复安装不同环境，我对dependency合并了，可能有冲突，2.这个extra_url在我的默认pip的trusted源中，我遗漏了，3.使用的有两个（1）python版本3.7,torch是1.13,完成ipynb中任务；（2）3.12+2.5完成的qwen 4.我提供的qwen2 链接中的readme有提到Transformers等版本的问题


总之，我今天会用一个clean的机器，重新复现一遍环境问题，然后更新一下

**Comment by idejie** [comment]
二、代码问题：（1）确实是在删代码（出空）时删多了或写错了，抱歉，应该按你写的修正 

（2）目前可能还有其他bug: 新版本的torch.nn.CELoss会计算softmax,因此在model中不需要重复计算（但是旧版本的torch建议再检查一下）

**Comment by idejie** [comment]
实现提示：（1）这个不准确，我在复现是为了快速，所以只用了train，理论上应该train 分成新的train(0.9)+val(0.1)，原始的val作为测试  （2）让大家实现colate_function的就是要注意这个问题 （3）trainer确实自己写的，也需要同学们修改 （4）这个看你train_loop的实现，如果是net()则调用forward的，如果是net.xx_forward则调用对应函数

**Comment by idejie** [comment]
四，建议：再次感谢你的建议个指正，今天我会用一个clean的环境重新复现一遍

**Comment by bucket-xv** [comment]
辛苦助教一一回应了，这种作业验证起来确实非常麻烦
