### ISSUE TITLE
ERROR: Failed building wheels

### ISSUE THREAD

**Issue by VincentArak** [idejie/mml-assignment3#11]
我是mac m系芯片，无法安装python3.7，从3.8到3.12都试了一遍。
ERROR: Failed building wheel for Pillow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy, matplotlib, Pillow)

**Comment by idejie** [comment]
我刚刚测了m芯片，可以安装，请自行解决（可以换几个版本的pillow

**Comment by VincentArak** [comment]
我想要知道您完整地安装流程

**Comment by VincentArak** [comment]
我好像解决了这个error的问题，build wheel 失败的时候用conda install补充一下对应的包
