### ISSUE TITLE
Transformer部分relative error过大

### ISSUE THREAD

**Issue by VincentArak** [idejie/mml-assignment3#13]
学长，我在transformer部分遇到了一些问题，我自认为正确实现了multi-head attention以及position encoding，但是relative error是1.0，我被这个问题困扰了一段时间，反复debug了我的代码，我想问题可能出在dropout部分，dropout的随机性在不同设备上会不会有所差异，导致最后的结果有很大的不同？
我的RNN部分已经全部做完，所有error都特别小，对于transformer部分，我不知道您可不可以提供一个没有使用dropout的版本？

**Comment by idejie** [comment]
建议尝试一下不同torch版本

**Comment by zyjjjjjjjj** [comment]
我也有一样的问题，请问最后用的哪个版本的torch

**Comment by VincentArak** [comment]
那我试试换一个torch版本吧。。。

**Comment by xkq1qkx** [comment]
请问换pytorch 版本的成功了没有~
