### ISSUE TITLE
3.2 Section A (5) 相对误差

### ISSUE THREAD

**Issue by jasondayuan** [idejie/mml-assignment3#14]
助教好，3.2 Section A (5)里面说误差数量级应该在e-5左右，但是我3.2 Section A (3)(4)的结果都符合相应的误差数量级的要求（所以感觉实现得应该也没什么问题），结果3.2 Section A (5)算出来的误差差不多2e-3和e-5差的有点远，后来查了几遍也没看出来哪里有问题，所以想问一下正确实现的话这道题误差真的可以在e-5左右吗？谢谢助教！

**Comment by SalineKleine** [comment]
我遇到了同样的问题，可以请问同学您是怎么解决的吗

**Comment by idejie** [comment]
检查一下dropout之类

**Comment by xkq1qkx** [comment]
可以问一下其他同学是怎么解决的ma~?
