### ISSUE TITLE
Transformer SectionB能否修改其他代码

### ISSUE THREAD

**Issue by slavic-codeman** [idejie/mml-assignment3#15]
想请问一下助教实现GPT2+CLIP的image captioning是只允许修改ipynb里指定的dataset和train部分，还是可以修改其他部分代码，只要是使用GPT2+CLIP即可呢？

**Comment by idejie** [comment]
都可以，以能实现训练和推理为整体目标。（代码只提供了一个基础的框架，需要同学动手完善
