### ISSUE TITLE
python 3.10环境，安装mml/requirement.txt中包时出错

### ISSUE THREAD

**Issue by cuiheling** [idejie/mml-assignment3#17]
ERROR: Could not find a version that satisfies the requirement torch==2.0.0+cu118 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for torch==2.0.0+cu118

**Comment by idejie** [comment]
可以参考pytorch 的安装方法:conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.8 -c pytorch -c nvidia

**Comment by idejie** [comment]
或者：pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118

**Comment by xkq1qkx** [comment]
我的经验告诉我尽量conda 装，不要pip装

**Comment by idejie** [comment]
> 我的经验告诉我尽量conda 装，不要pip装

pip、conda都可以，甚至还有其他方法，各有各的优势，以能解决自己的问题为最佳
