### ISSUE TITLE
Section2PartA: dropout

### ISSUE THREAD

**Issue by VincentArak** [idejie/mml-assignment3#19]
<img width="613" alt="Screenshot 2024-12-18 at 13 53 52" src="https://github.com/user-attachments/assets/8eeed665-fbfc-4680-91e5-393202c2a1e6" />
学长，从这张图可以看到，差异的来源是dropout没有把一个元素弄成0.
对于您来说把dropout弄掉再生成一份可能会花一些时间，但是对于我（一个mac系统没有cuda不知道精确版本搭配的人）来说，尝试各种别的方式花的时间可能会更多，所以抱歉在这个问题上一再麻烦您。

**Comment by idejie** [comment]
也许，你可以用colab。。。。

**Comment by idejie** [comment]
这个问题如果你还没有解决，可以微信我
