### ISSUE TITLE
Section2 PartB Softmax问题

### ISSUE THREAD

**Issue by slavic-codeman** [idejie/mml-assignment3#20]
mml/model/model.py中的train forward函数，不需要手动计算softmax，因为crossentropy loss会自动计算，这样算会导致重复计算，梯度很难更新，结果就是总是loss是10.多不下降，希望对大家有所帮助！

**Comment by amannier** [comment]
Greate!

**Comment by amannier** [comment]
Great!

**Comment by idejie** [comment]
相似问题:https://github.com/idejie/mml-assignment3/issues/23
