### ISSUE TITLE
数据集相关问题

### ISSUE THREAD

**Issue by 2628372574** [idejie/mml-assignment3#21]
当运行python mml/training.py --checkpoint-name small_model.pt --size S时，出现以下报错
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\HomeWork\\多模态\\multimodal-hw03\\mml-assignment3-main\\mml\\data\\coco\\images\\306798'
其实肯定是缺少了这个数据，但是我想知道这个数据是从哪里来的
在ipynb的提示下，一共下了train_captions，training_images和validation_images这三个数据集相关的文件
其中，只说明了train_captions的路径应该是mml/data/coco/annotations，并没有说明下面两个图片文件的路径
下面两个图片中也没有images子文件夹，而其中的命名也是“COCO_train2014_000000000009”这样的，并没有一个纯数字命名
在根目录中搜索整个文件夹里也没有306798这个文件
所以这个文件是怎么来的

**Comment by idejie** [comment]
这个我也没遇到过，可能要检查一下代码了
