### ISSUE TITLE
section 3.2A dropout相关

### ISSUE THREAD

**Issue by Ringwzf** [idejie/mml-assignment3#22]
![mmexport1734593947453](https://github.com/user-attachments/assets/35afc8a9-8e25-4265-99c9-abb4b003aa3f)
<img width="448" alt="mmexport1734593949628" src="https://github.com/user-attachments/assets/71061c29-778f-4716-9118-1cc2a9bb91f8" />
已经确认过相同的代码在不同环境下（具体为pytorch版本）所得的结果不同，请问可否提供重新一个环境的requirements，指定python与pytorch的版本？

**Comment by idejie** [comment]
目前我使用的是3.7+1.13

**Comment by idejie** [comment]
我今天会在确认一版结果

**Comment by idejie** [comment]
同学你好，经过反复确认，这个题目在colab上可以正确执行

**Comment by idejie** [comment]
一个新版本下的基础依赖：https://github.com/idejie/mml-assignment3/blob/main/py3.10-torch2.5-req.txt
这个确认过正确执行
