### ISSUE TITLE
修改max_lr为1后似乎有些问题

### ISSUE THREAD

**Issue by AstroCIEL** [idejie/mml-assignment3#24]
按照原来没有修改max_lr的时候，看起来训的挺正常的：
![image](https://github.com/user-attachments/assets/e2f67225-fb4c-4ff3-b47a-39277cbfcdcd)

但是按照今天下午发布的说明改成1后：
![image](https://github.com/user-attachments/assets/be312d54-d68f-45db-8522-371d995fff49)
![image](https://github.com/user-attachments/assets/72ed7535-4180-4cc5-a87f-bf729d10aa1f)

我想确认一下真的需要改成1吗，还是其他什么地方需要一同修改但是我遗漏了？

**Comment by idejie** [comment]
也许你可以保留原来使用的方法，改之前是在py3.7+torch1.13,如果你用的更新的版本，可以用改之后的
