### ISSUE TITLE
一直未解决Task3-2 SectionA(5)中的error过大问题！！！为什么close了?

### ISSUE THREAD

**Issue by xkq1qkx** [idejie/mml-assignment3#25]
老问题，但助教的建议是换torch版本。。。
但是问题是torch版本跟cuda 版本有版本依赖；同时numpy版本也与torch版本有依赖
cuda版本还和显卡驱动版本有依赖
我已经在环境配置上花了超长的时间了。。。好不容易装出来一个能跑通的环境
而且从最后的训练效果来看也还可以，loss=0.03667（略大于要求的0.03）
就非得卡这个1e-5？

**Comment by idejie** [comment]
1.sectionA不需要cuda版本的torch，请仔细阅读题目。
2.numpy请使用1.x版本的，
3.cuda版本确实和驱动有依赖，但pytorch提供了很多cuda版本的
4.没清楚你说的1e-5是什么意思，你可以补充回答

在我复现过程中，在国内镜像下配置环境应该花不了10分钟

**Comment by idejie** [comment]
如果你有问题可以re-open this issuse
