### ISSUE TITLE
在3.1中，很多关于inspect或者sample的都会出现以下报错

### ISSUE THREAD

**Issue by 2628372574** [idejie/mml-assignment3#26]
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-37-7f44709ade10> in <module>
     10 
     11     for gt_caption, sample_caption, url in zip(gt_captions, sample_captions, urls):
---> 12         img = image_from_url(url)
     13         # Skip missing URLs.
     14         if img is None: continue

d:\HomeWork\多模态\multimodal-hw03\mml-assignment3-main\mml\image_utils.py in image_from_url(url)
     63             ff.write(f.read())
     64         img = imread(fname)
---> 65         os.remove(fname)
     66         return img
     67     except urllib.error.URLError as e:

PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\hp\\AppData\\Local\\Temp\\tmp_ozabdw4'

但是其他的error都在规定范围内，请问这个问题是否重要，要怎么解决

**Comment by idejie** [comment]
1.看起来是你网络的问题，某个图像的url加载不出来图像
2.可以修改image_from_url方法（参考历史issue：https://github.com/idejie/mml-assignment3/issues/4），变为直接加载本地图像
