### ISSUE TITLE
请问3.2B Image Captioning with CLIP and LM正常训练时间大概是多久

### ISSUE THREAD

**Issue by zyjjjjjjjj** [idejie/mml-assignment3#28]
我用的configS，提前用CLIP处理好了数据集，在3090上一个epoch要训12~13分钟，150个epoch的话就是30个小时，这是正常的吗

**Comment by Ringwzf** [comment]
同问，我现在在本地训练使用全部数据集的话，一个epoch的时间可能长达约1.5h

**Comment by idejie** [comment]
如果想加速，请提前处理好图像和文本特征，例如使用CLIP提取图像的embedding（pooled and last state）,保存成pickle、hdf5等，再在dataset中load

以上为个人实验，仅供参考

**Comment by idejie** [comment]
> 我用的configS，提前用CLIP处理好了数据集，在3090上一个epoch要训12~13分钟，150个epoch的话就是30个小时，这是正常的吗

150个epoch有点多了，注意看valid loss是不是趋于稳定了，可以early stop

另外可以引入一些评价指标，估测生成的caption好坏，如https://github.com/huggingface/evaluate/blob/main/metrics/bleu/README.md

仅供参考
