### ISSUE TITLE
关于3.1 sectionB误差相关问题

### ISSUE THREAD

**Issue by ltwyx** [idejie/mml-assignment3#30]
如果我的backward误差很大但是后面的loss和test time都没有问题可以算作是backward实现正确吗，因为重新配一个对应的pytorch和cuda确实很麻烦而且还不确定会不会导致forward误差也发生错误

**Comment by ltwyx** [comment]
顺便问一下教学网的期中分数怎么变成尚未评分了（

**Comment by idejie** [comment]
相似问题，在历史issue解答过，可以参考，目前比较好的解决办法在colab上运行
