### ISSUE TITLE
关于训练速度的问题以及 该pipeline效率的疑问

### ISSUE THREAD

**Issue by xkq1qkx** [idejie/mml-assignment3#31]
在最后训练环节有几个疑问
## ConfigL下训练：
<img width="1053" alt="截屏2024-12-29 03 01 32" src="https://github.com/user-attachments/assets/15b3dcae-290d-447d-b0be-1dbf228b26e9" />
想请教助教和其他同学，关于这个Warning该怎么解决，会影响训练效率吗？以及这个训练速度超级慢（26s/it）是正常的嘛？

## ConfigS下训练：

如果每个batch单独加载图片、encode的话速度如下
<img width="1053" alt="截屏2024-12-29 03 10 55" src="https://github.com/user-attachments/assets/666f0549-f1d9-427c-b347-ee0eb935eb69" />
如果在一开始一次性加载所有图片、全部encode的话速度：
<img width="805" alt="截屏2024-12-29 04 15 08" src="https://github.com/user-attachments/assets/959d9aa3-cdf6-4cde-b91b-22fae8e09fe2" />
但是全部加载图片的过程中会出现"Killed"，我猜测是存不下了，请问助教这个的本意是逐batch的加载图像还是全部一次性加载呀，以及怎么避免超内存的问题呢

**Comment by idejie** [comment]
1.这个warning，需要你定位出具体代码的位置，我可能才知道是哪里有问题，从截图看不出

2.逐batch加载，但是每个batch中可能有一些操作，比如句子不一样长，需要有一些pad或者pack的操作

3.为节省内存，可以提前处理好图像、文本特征
