### ISSUE TITLE
奇怪的 loss曲线

### ISSUE THREAD

**Issue by HuangXuchuan** [idejie/mml-assignment3#32]
![image](https://github.com/user-attachments/assets/23bc7a1e-f6bc-4a68-87f6-b04806a11673)
将model.py第272行注释后，
出现了这样的loss曲线，这可能是什么问题呢？

**Comment by idejie** [comment]
1.建议检查梯度
2.如果梯度消失或者过大，可以用torch的clip_norm梯度裁剪
3.建议减小学习率
