### ISSUE TITLE
Task3-2 SectionA(5)中的error过大问题

### ISSUE THREAD

**Issue by cuiheling** [idejie/mml-assignment3#33]
![image](https://github.com/user-attachments/assets/13cec660-5c0e-45ba-86af-cdb88159b089)
![image](https://github.com/user-attachments/assets/7c487020-1c0b-4638-ad3e-e39792fbcfcd)
这个1e-5的界是不是有些太紧了？代码给出的expected_scores精度太低，导致正常算的error都在1e-3左右，我看其他同学也是这样

**Comment by idejie** [comment]
这个应该没那么紧，建议在colab上试试（同学装的torch或者numpy济南有问题
