### ISSUE TITLE
3.1-RNN_Captioning.ipynb的Inspect the data部分频繁报错

### ISSUE THREAD

**Issue by faizwh** [idejie/mml-assignment3#4]
在测试Inspect the data部分时除了URL Error:  Not Found ……之外发现经常发生如下报错，想请问大家是怎么回事（抱拳）
![image](https://github.com/user-attachments/assets/c9a50c03-0663-4e8b-8606-f31071a97a19)

**Comment by faizwh** [comment]
现将image_from_url(url)修改为如下形式，能获取图片，仅发生URL Error: Not Found ……这一错误，想请问这样的改动是否会产生其他影响
def image_from_url(url):
    """
    Read an image from a URL. Returns a numpy array with the pixel data.
    We write the image to a temporary file then read it back. Kinda gross.
    """
    try:
        f = urllib.request.urlopen(url)
        """
         _, fname = tempfile.mkstemp()
        with open(fname, "wb") as ff:
            ff.write(f.read())
        img = imread(fname)
        """
        with tempfile.NamedTemporaryFile(delete=False) as temp:
            temp.write(f.read())
            temp.flush()
            img = imread(temp.name)
        os.remove(temp.name)
        #os.remove(fname)
        return img
    except urllib.error.URLError as e:
        print("URL Error: ", e.reason, url)
    except urllib.error.HTTPError as e:
        print("HTTP Error: ", e.code, url)

**Comment by idejie** [comment]
（1）上面报错是网络问题，（2）你的修改没问题

**Comment by faizwh** [comment]
> （1）上面报错是网络问题，（2）你的修改没问题

感谢学长🙏🙏

**Comment by cuiheling** [comment]
请问这个“网络问题”应该如何解决啊

**Comment by idejie** [comment]
url替换成直接读取图像地址，再用PIL或opencv打开

**Comment by cuiheling** [comment]
刚刚将url换成了这位faizwh同学的代码，出现了新的报错，请问如何解决？

**Comment by cuiheling** [comment]
原来的报错也没有解决
![微信图片_20241220164819](https://github.com/user-attachments/assets/8e38b974-5bdd-4533-8971-03a3ba7533d7)

**Comment by cuiheling** [comment]
新报错是这样的（小概率不出现上面的报错时就会这样，但其实修改之前也会出现）
![微信图片_20241220165053](https://github.com/user-attachments/assets/823b69ac-e591-4c29-891f-37c75cd37bff)

**Comment by cuiheling** [comment]
问题似乎解决了，谢谢！

**Comment by idejie** [comment]
> 请问这个“网络问题”应该如何解决啊

需要科学上网

**Comment by idejie** [comment]
> 问题似乎解决了，谢谢！

nice~
