### ISSUE TITLE
Instructions for (2)Recurrent Neural Network [5pts]

### ISSUE THREAD

**Issue by HuangXuchuan** [idejie/mml-assignment3#5]
Hi there!
对于(2)Recurrent Neural Network [5pts]，我似乎并没有在rnn_layers.py中找到待完成的代码TODO部分，请问这部分需要自己自己写函数/类吗？

**Comment by idejie** [comment]
请仔细阅读要求，既要补全mml/rnn_layers.py，也要补全mml/classifiers/rnn.py（这个问题不应该在QA范围内
