### ISSUE TITLE
请问电脑没有Nvidia显卡，没装cuda11.8可以配置mml/requirements.txt的环境吗

### ISSUE THREAD

**Issue by LinkLanze** [idejie/mml-assignment3#6]
![屏幕截图 2024-12-11 213657](https://github.com/user-attachments/assets/0ab03a7f-5257-46f2-a491-9962b66f24a1)

**Comment by idejie** [comment]
建议使用colab（需要科学上网）或者租用国内的一些gpu平台，本次作业显存要求不高在11-12G就苦于
