### ISSUE TITLE
关于数据的问题

### ISSUE THREAD

**Issue by slavic-codeman** [idejie/mml-assignment3#8]
mml/data/dataset.py中最上面有注释“ ImageCaptionDataset loads data from pickle file and returns image embedding and caption.”，我想问一下这个pickle file是指的train_caption.json文件和COCO的图片吗，还是有别的.pkl文件呢？

**Comment by idejie** [comment]
可以自行实现，以上只是题目的提示且是答案的一种，该题并非只有一个标准答案，完成一个可以loadcoco图-文数据的dataset即可
